### ISSUE TITLE
Spacing on http://intermezzos.github.io/book/

### ISSUE THREAD

**Issue by photomattmills** [intermezzOS/book#1]
I can't seem to repro locally, but a lot of words seem to be missing spaces between
(e.g. <img width="180" alt="ss of problem text" src="https://cloud.githubusercontent.com/assets/148374/12000589/5c4dbf8a-aa8e-11e5-8e7b-101390527341.png"> from the first paragraph). I'm on OSX Yosemite with Chrome. Could be it just needs a re-deploy?

**Comment by steveklabnik** [comment]
It's an upstream bug of an upstream bug, actually: https://github.com/azerupi/mdBook/issues/76

**Comment by AnthIste** [comment]
+1 for OSX Yosemite and Chrome

**Comment by photomattmills** [comment]
@steveklabnik would you accept a PR of the newlines converted to spaces in the meantime? I figured out the regex/replace for it, wouldn't be hard. I don't want to mess with anyone's workflow, though.

**Comment by flounders** [comment]
I'm experiencing the same thing with Arch and Firefox. I think just replacing the newlines with spaces will fix the issue for the browser, but reading through the markdown files would be a pain. The better solution would be to prefix the newline with a space or postfix it. That way the formatting is more a less preserved in markdown and on the page. Ideally the bug should be fixed in upstream.

**Comment by steveklabnik** [comment]
@mattmills I share @flounders 's opinion, we should just fix this upstream. It might be a bit awkward for a few days, but that's better than reformatting everything and then reformatting it back, I'd say.

If it were going to be wrong upstream for _months_, then I'd consider it.

**Comment by photomattmills** [comment]
@steveklabnik fine with me. Still a bit odd that it doesn't build that way on my local machine.

**Comment by photomattmills** [comment]
Going to close this since the upstream stuff appears to be fixed. Thanks!
