### ISSUE TITLE
Confusing wording in section 3.2

### ISSUE THREAD

**Issue by neunenak** [intermezzOS/book#120]
Current text is
"Okay, so we copied four hexadecimal digits into memory, right? For our H. 0248. A hexadecimal digit has sixteen values, so two of them are 32. Since we need one word for the colors, and one word for the H, that’s two words. Hence, if our first memory position is at 0, the second letter will start at 2."

and this is definitely confusing. I suppose what you want to say is something like 

"A hexadecimal digit has sixteen values and takes up four bits (since 2^4 = 16), so a sequence of two hexadecimal digits requires one 8-bit byte, and four hexadecimal digits take up two bytes. Hence, if our first memory position is at 0, the second letter will start at 2".

**Comment by Seeker14491** [comment]
Agreed, it's confusing and incorrect.

I like your alternate explanation, though I would make it clear that:
- Our computers are byte-oriented, meaning that consecutive addresses are 1 byte apart
- We used `mov word`, and a `word` is 2 bytes, thus we move over 2 spots. So even if instead of the `0x0248` representing `H` we moved the 1 byte number 0x20 (a black space character on a black background), we still would have to move over 2 spots, as the missing digits are assumed to be zero.

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition yet, and it's not likely to make it exactly. If someone wants to send in a PR to fix up the first edition, please feel free!
