### ISSUE TITLE
Paging Bits (Endianess?) 

### ISSUE THREAD

**Issue by Mattman22** [intermezzOS/book#163]
In section 4.1 is says 0b11 sets the first two bits, but these bits are later set (along with another) with 0b10000011. That would make it seem like the last two bits to me. Is it because it's in little-endian? 

http://intermezzos.github.io/book/paging.html#pointing-the-entries-at-each-other

**Comment by dato** [comment]
The wording in the book could be improved as follows: substitute “bits 1 and 0” for “first two bits” (and use “bit 0” instead of “the first bit”).

@Mattman22: In registers (and bit flags in general) bits are numbered from right to left (from least significant to most). So the right-most bit is “first” in such numbering.

These references to bit positions are unrelated to endianness. As far as I know, “bit 0” is always the least significant one.

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition yet, and it's not likely to make it exactly. If someone wants to send in a PR to fix up the first edition, please feel free!
