### ISSUE TITLE
Book index page needs styles

### ISSUE THREAD

**Issue by steveklabnik** [intermezzOS/book#183]
Should look somewhat similar to the main page.

**Comment by ducks** [comment]
I started to look into this one and have discovered a few things and have a few questions as well.

The first thing I noticed is that the book index is outside both of the mdbook build directories. This forces a link directly into `first-edition/src/theme/book.css`. 

Because of this I decided to try and reorganize the book so that it all could be built with one command.
I've done this in a branch here: https://github.com/ducks/book-1/tree/rearrange-layout-gh-183

There are issues with this, and they may be why you chose to break it into two builds.
The first is that both versions are now shown in the sidebar at all times. I can see how this might be confusing. The other thing that seems to break is appendices. These could probably be moved to normal chapters but that's up to y'all.

I then decided to just link to the book theme css and that branch is here:
https://github.com/ducks/book-1/tree/style-index-page-gh-183

This is probably easiest and quickest, but more likely to break down the line if anything does happen to change.

Let me know which way you'd prefer, and I can get a PR going!

**Comment by steveklabnik** [comment]
> There are issues with this, and they may be why you chose to break it into two builds.

Yup! I'd much rather keep them separate :)

> I then decided to just link to the book theme css and that branch is here:

This looks great! A PR for this would be awesome :)
