### ISSUE TITLE
grub-mkrescue fails with "Cannot find path 'efi.img' in loaded ISO image" (re-opened with different solution)

### ISSUE THREAD

**Issue by LaylBongers** [intermezzOS/book#76]
This is #45 re-opened. A stock arch install with only the basic tools in the book's list installed will give this error. The solution without installing mtools (which is tools for MSDOS disks) is to add a parameter to the grub-mkrescue command.

```
grub-mkrescue -d /usr/lib/grub/i386-pc/ -o os.iso isofiles
```

This will tell grub-mkrescue to use BIOS rather than EFI.

http://intermezzos.github.io/book/making-an-iso.html

**Comment by xerz-one** [comment]
This tutorial is on 64-bit kernels - and since most of x64 PCs come bundled with UEFI or Apple EFI, seems like using EFI is the way to go, hence installing `mtools` is still correct.

_(Edit: yes, I forgot, QEMU works with BIOS by default... oh well)_ 

Anyway, if you want to support BIOS, your solution is right. Would require on a Debian system to install `grub-pc-bin`, for instance - **not `grub-pc` though**, since that would uninstall an existing EFI boot.

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition, as we no longer use GRUB. If someone wants to send in a PR to fix up the first edition, please feel free!
